#Autor: LAH
#Version 1.0

# Set the base image
FROM node:16.13.1

#Install ssh stuff
RUN apt-get update  -y \
    && apt-get upgrade -y \ 
    && apt-get install -y \
    ssh \
    sshpass \
    sudo \
    software-properties-common

#Creates and set the working directory
WORKDIR /home/ansible_controller

#Copy ssh script
COPY startup.sh .

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Copy the project files to the container
COPY ./public ./public
COPY ./src ./src

#Install dependencies
RUN npm install

#Expose port
EXPOSE 3000

#Set user and password
RUN useradd -rm -d /home/ansible_controller -s /bin/bash -g root -G sudo -u 1001 ansible_controller
RUN echo ansible_controller:12345 | chpasswd

#Avoids asking for password
RUN echo "ansible_controller ALL=(ALL:ALL) NOPASSWD: ALL" |  EDITOR="tee -a"  visudo

#Creates .ssh dir
RUN mkdir -p /home/ansible_controller/.ssh

#Runs ssh script and starts the hello-world app
CMD ["/bin/bash", "/home/ansible_controller/startup.sh"]
