#Autor: LAH
#Version 1.0

# Set the base image
FROM node:16.13.1

#Install ssh stuff
RUN apt-get update  -y \
    && apt-get upgrade -y \ 
    && apt-get install -y \
    ssh \
    sshpass \
    sudo \
    software-properties-common

#Set user and password
RUN useradd -rm -d /home/lucy -s /bin/bash -g root -G sudo -u 1001 lucy
RUN echo lucy:passlucy | chpasswd

#Avoids asking for password
RUN echo "lucy ALL=(ALL:ALL) NOPASSWD: ALL" |  EDITOR="tee -a"  visudo


#Creates and set the working directory
WORKDIR /home/lucy

#Copy ssh script
COPY startup.sh .

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Copy the project files to the container
COPY ./public ./public
COPY ./src ./src

#Install dependencies
RUN npm install

#Creates .ssh dir
RUN mkdir -p /home/lucy/.ssh

EXPOSE 3000

#Runs ssh script and starts the hello-world app
CMD ["/bin/bash", "/home/lucy/startup.sh"]
