name:  Test workflow

on:
  push: 
  pull_request: 
  workflow_dispatch:

jobs:
    myfirstjob:
              name: Run tests
              runs-on: ubuntu-latest
              steps:
              - name: Load repository
                uses: actions/checkout@v3

              - name: Install node
                run: | 
                      sudo apt update 
                      sudo apt install nodejs=16.13.1

              - name: Install dependencies
                run:  npm install

              - name: Run tests
                run:  npm run tests


    
    
