name:  Test workflow

on:
  push: 
  pull_request: 
  workflow_dispatch:

jobs:
    testJob:
              name: Run tests
              runs-on: ubuntu-latest
              steps:
              - name: Load repository
                uses: actions/checkout@v3

              - name: Install dependencies
                run:  | 
                      cd capstone_project/hello-world/
                      npm install
                      pwd
                      ls                     
              - name: Run tests
                run: |
                      cd capstone_project/hello-world/
                      npm run test
                id: nodetest
                
    runContainerJob:  
                    needs: [testJob]
                    name: Build container
                    runs-on: ubuntu-latest
                    steps:    
                    - name: Run container
                      if: ${{ steps.test.outcome == 'success' }}
                      run: |
                            cd capstone_project/hello-world/
                            pwd
                            docker build -t hello-world-img .
                            docker run --name hello-world -p 3000:3000 -itd hello-world-img
                            docker ps
                      
                    - name: Not run the container
                      if: ${{ steps.test.outcome != 'success' }}
                      run: echo ${{ steps.test.outcome}}
                      


    
    
