name:  Test workflow

on:
  push: 
  pull_request: 
  workflow_dispatch:

jobs:
    myfirstjob:
              name: Run tests
              runs-on: ubuntu-latest
              steps:
              - name: Load repository
                uses: actions/checkout@v3

              - name: Install dependencies
                run:  | 
                      cd capstone_project/hello-world/
                      npm install
                      pwd
                      ls                     
              - name: Run tests
                run: |
                      cd capstone_project/hello-world/
                      npm run test
                id: nodetest
                
              - name: Run container
                if: ${{ steps.test.outcome == 'success' }}
                run: |
                      docker build -t hello-world-img .
                      docker run --name hello-world -p 3000:3000 -itd hello-world-img
                      docker ps


    
    
